//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerSidePaginationWithDataTableMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order1 = new HashSet<Order>();
        }
    
        public int OrderId { get; set; }
        public long OrderNumber { get; set; }
        public int CustomerId { get; set; }
        public string CustomerInstructions { get; set; }
        public string InternalNotes { get; set; }
        public System.DateTime OrderDate { get; set; }
        public bool IsQuote { get; set; }
        public byte[] RowVersion { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
        public Nullable<decimal> ShippingTotal { get; set; }
        public Nullable<decimal> DiscountTotal { get; set; }
        public Nullable<decimal> TAX { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<int> TaxRateId { get; set; }
        public int PaymentStatus { get; set; }
        public int ShipStatus { get; set; }
        public int OrderStatus { get; set; }
        public string OrderType { get; set; }
        public Nullable<int> ParentOrderId { get; set; }
        public string Channel { get; set; }
        public string ChannelOrderid { get; set; }
        public Nullable<decimal> InsuranceTotal { get; set; }
        public bool QBExported { get; set; }
        public bool IsTaxCollected { get; set; }
        public string TaxCounty { get; set; }
        public int MarketPlaceProfileID { get; set; }
        public Nullable<int> ApplyPayments_ApplyPaymentId { get; set; }
        public string MarketPlace_ItemID { get; set; }
        public string CarrierXMLRequestInput { get; set; }
        public string CarrierXMLResponseOutput { get; set; }
        public bool IsDeleted { get; set; }
        public string PackageStatus { get; set; }
        public Nullable<System.DateTime> LablePrintingDate { get; set; }
        public Nullable<System.DateTime> LastChecked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order1 { get; set; }
        public virtual Order Order2 { get; set; }
    }
}
